<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>إدارة المخزون والأسعار - نظام إدارة المقهى</title>
    
    <!-- CSS Files -->
    <link rel="stylesheet" href="../css/money.css">      <!-- For sidebar and general layout -->
    <link rel="stylesheet" href="../css/inventory.css">  <!-- Styles for this page -->
    <link rel="stylesheet" href="../css/modal.css">      <!-- [الإصلاح الجذري] تمت إعادة إضافة هذا الملف المهم -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body>
    <div id="overlay" class="overlay"></div>
    <div class="sidebar-toggle" id="sidebarToggle"><i class="fas fa-bars"></i></div>

    <!-- Sidebar -->
    <div id="sidebar" class="sidebar">
        <div class="sidebar-header"><div class="logo-container"><img src="/uploads/logo.png" alt="Logo" class="logo-img"><div class="logo-text"><h3>مقهى النجمة</h3><span>نظام الإدارة</span></div></div></div>
        <nav class="sidebar-nav"><ul class="nav-list"><li><a href="money.php" class="nav-link"><i class="fas fa-wallet"></i><span>النقدية</span></a></li><li><a href="devices.php" class="nav-link"><i class="fas fa-desktop"></i><span>الأجهزة</span></a></li><li><a href="tables.php" class="nav-link"><i class="fas fa-table"></i><span>التربيزات</span></a></li><li><a href="orders.php" class="nav-link"><i class="fas fa-shopping-cart"></i><span>الأوردرات</span></a></li><li><a href="inventory.php" class="nav-link active"><i class="fas fa-boxes"></i><span>المخزن والأسعار</span></a></li><li><a href="customer.php" class="nav-link"><i class="fas fa-users"></i><span>العملاء</span></a></li><li><a href="employees.php" class="nav-link"><i class="fas fa-user-tie"></i><span>الموظفين</span></a></li><li><a href="setting.php" class="nav-link"><i class="fas fa-cog"></i><span>الإعدادات</span></a></li><li><a href="reports.php" class="nav-link"><i class="fas fa-chart-bar"></i><span>التقارير</span></a></li></ul></nav>
        <div class="sidebar-footer"><div class="user-profile"><div class="user-avatar"><img src="/uploads/employee.jpg" alt="Employee"><div class="status-dot"></div></div><div class="user-info"><span class="user-name">محمد حامد</span><span class="user-role">مدير النظام</span></div></div><button class="logout-btn"><i class="fas fa-sign-out-alt"></i><span>تسجيل الخروج</span></button></div>
    </div>

    <!-- Main Content -->
    <div class="main-content">
        <header class="page-header"><div class="header-content"><div class="page-title"><h1>إدارة المخزون والأسعار</h1><p>تتبع ومراقبة جميع المنتجات والأسعار</p></div><div class="header-actions"><button class="action-btn secondary" id="exportInventoryBtn"><i class="fas fa-download"></i><span>تصدير</span></button><button class="action-btn icon-only" id="refreshInventoryBtn"><i class="fas fa-sync-alt"></i></button></div></div></header>

        <div class="financial-cards">
            <div class="card balance-card"><div class="card-header"><div class="card-icon"><i class="fas fa-boxes"></i></div></div><div class="card-body"><h3>إجمالي المنتجات</h3><div class="amount"><span class="value" id="totalProductsCount">0</span><span class="currency">منتج</span></div></div></div>
            <div class="card expenses-card"><div class="card-header"><div class="card-icon"><i class="fas fa-exclamation-triangle"></i></div></div><div class="card-body"><h3>قليلة المخزون</h3><div class="amount"><span class="value" id="lowStockProductsCount">0</span><span class="currency">منتج</span></div></div></div>
            <div class="card revenues-card"><div class="card-header"><div class="card-icon"><i class="fas fa-tags"></i></div></div><div class="card-body"><h3>الأقسام</h3><div class="amount"><span class="value" id="totalCategoriesCount">0</span><span class="currency">قسم</span></div></div></div>
            <div class="card notes-card"><div class="card-header"><div class="card-icon"><i class="fas fa-money-bill-wave"></i></div></div><div class="card-body"><h3>قيمة المخزون</h3><div class="amount"><span class="currency">ج</span><span class="value" id="inventoryValue">0.00</span></div></div></div>
        </div>

        <div class="tab-navigation">
            <button id="devices-pricing-tab" data-tab="devices-pricing" class="tab-btn active"><i class="fas fa-desktop"></i><span>أنواع الأجهزة</span></button>
            <button id="buffet-products-tab" data-tab="buffet-products" class="tab-btn"><i class="fas fa-coffee"></i><span>منتجات البوفيه</span></button>
            <button id="categories-tab" data-tab="categories" class="tab-btn"><i class="fas fa-tags"></i><span>أقسام المنتجات</span></button>
            <button id="coupons-tab" data-tab="coupons" class="tab-btn"><i class="fas fa-ticket-alt"></i><span>كوبونات الخصم</span></button>
        </div>

        <!-- Tab Contents -->
        <div id="devices-pricing-content" class="tab-content active"><div class="devices-section"><div class="section-header"><h3>أنواع الأجهزة والأسعار</h3><button class="add-device-btn" id="addDeviceTypeModalBtn"><i class="fas fa-plus"></i><span>إضافة نوع</span></button></div><div class="devices-grid" id="deviceTypesGrid"></div></div></div>
        <div id="buffet-products-content" class="tab-content"><div id="dynamic-products-container"></div></div>
        <div id="categories-content" class="tab-content"><div class="devices-section"><div class="section-header"><h3>أقسام المنتجات</h3><button class="add-device-btn" id="addCategoryModalBtn"><i class="fas fa-plus"></i><span>إضافة قسم</span></button></div><div class="devices-grid" id="categoriesGrid"></div></div></div>
        <div id="coupons-content" class="tab-content"><div class="devices-section"><div class="section-header"><h3>الكوبونات النشطة</h3><button class="add-device-btn" id="addCouponModalBtn"><i class="fas fa-plus"></i><span>إضافة كوبون</span></button></div><div class="devices-grid" id="activeCouponsGrid"></div></div><div class="section-separator"></div><div class="devices-section"><div class="section-header"><h3>الكوبونات المنتهية</h3></div><div class="devices-grid" id="expiredCouponsGrid"></div></div></div>
    </div>

    <!-- Modals -->
    <div id="addDeviceTypeModal" class="modal"><div class="modal-content"><div class="modal-header"><h3><i class="fas fa-plus-circle"></i> إضافة نوع جهاز</h3><span class="close-btn">&times;</span></div><form id="addDeviceTypeForm"><div class="form-group"><label for="deviceTypeName">اسم نوع الجهاز</label><input type="text" id="deviceTypeName" required></div><div class="form-group"><label class="checkbox-label"><input type="checkbox" id="hasRoom"><span class="checkmark"></span><span>يحتاج لغرفة</span></label></div><div class="form-row"><div class="form-group"><label for="singlePrice">سعر الفردي</label><input type="number" id="singlePrice" step="0.01" required></div><div class="form-group"><label for="multiPrice">سعر المتعدد</label><input type="number" id="multiPrice" step="0.01" required></div></div><div class="modal-footer"><button type="button" class="btn-cancel">إلغاء</button><button type="submit" class="btn-save">حفظ</button></div></form></div></div>
    <div id="editDeviceTypeModal" class="modal"><div class="modal-content"><div class="modal-header"><h3><i class="fas fa-edit"></i> تعديل نوع الجهاز</h3><span class="close-btn">&times;</span></div><form id="editDeviceTypeForm"><div class="form-group"><label for="editDeviceTypeName">اسم نوع الجهاز</label><input type="text" id="editDeviceTypeName" required></div><div class="form-group"><label class="checkbox-label"><input type="checkbox" id="editHasRoom"><span class="checkmark"></span><span>يحتاج لغرفة</span></label></div><div class="form-row"><div class="form-group"><label for="editSinglePrice">سعر الفردي</label><input type="number" id="editSinglePrice" step="0.01" required></div><div class="form-group"><label for="editMultiPrice">سعر المتعدد</label><input type="number" id="editMultiPrice" step="0.01" required></div></div><div class="modal-footer"><button type="button" class="btn-cancel">إلغاء</button><button type="submit" class="btn-save">حفظ</button></div></form></div></div>
    <div id="addProductModal" class="modal"><div class="modal-content"><div class="modal-header"><h3><i class="fas fa-plus-circle"></i> إضافة منتج</h3><span class="close-btn">&times;</span></div><form id="addProductForm"><div class="form-row"><div class="form-group"><label for="productName">اسم المنتج</label><input type="text" id="productName" required></div><div class="form-group"><label for="productCategory">القسم</label><select id="productCategory" required><option value="">اختر</option></select></div></div><div class="form-row"><div class="form-group"><label for="employeePrice">سعر الموظف</label><input type="number" id="employeePrice" step="0.01" required></div><div class="form-group"><label for="customerPrice">سعر العميل</label><input type="number" id="customerPrice" step="0.01" required></div></div><div class="form-row"><div class="form-group"><label for="productQuantity">الكمية</label><input type="number" id="productQuantity" min="0" required></div><div class="form-group"><label for="quantityUnit">الوحدة</label><select id="quantityUnit" required><option value="">اختر</option><option value="كوب">كوب</option><option value="زجاجة">زجاجة</option><option value="قطعة">قطعة</option></select></div></div><div class="form-group"><label for="productDescription">الوصف</label><textarea id="productDescription" rows="3"></textarea></div><div class="modal-footer"><button type="button" class="btn-cancel">إلغاء</button><button type="submit" class="btn-save">حفظ</button></div></form></div></div>
    <div id="editProductModal" class="modal"><div class="modal-content"><div class="modal-header"><h3><i class="fas fa-edit"></i> تعديل منتج</h3><span class="close-btn">&times;</span></div><form id="editProductForm"><div class="form-row"><div class="form-group"><label for="editProductName">اسم المنتج</label><input type="text" id="editProductName" required></div><div class="form-group"><label for="editProductCategory">القسم</label><select id="editProductCategory" required><option value="">اختر</option></select></div></div><div class="form-row"><div class="form-group"><label for="editEmployeePrice">سعر الموظف</label><input type="number" id="editEmployeePrice" step="0.01" required></div><div class="form-group"><label for="editCustomerPrice">سعر العميل</label><input type="number" id="editCustomerPrice" step="0.01" required></div></div><div class="form-row"><div class="form-group"><label for="editProductQuantity">الكمية</label><input type="number" id="editProductQuantity" min="0" required></div><div class="form-group"><label for="editQuantityUnit">الوحدة</label><select id="editQuantityUnit" required><option value="">اختر</option><option value="كوب">كوب</option><option value="زجاجة">زجاجة</option><option value="قطعة">قطعة</option></select></div></div><div class="form-group"><label for="editProductDescription">الوصف</label><textarea id="editProductDescription" rows="3"></textarea></div><div class="modal-footer"><button type="button" class="btn-cancel">إلغاء</button><button type="submit" class="btn-save">حفظ</button></div></form></div></div>
    <div id="addCategoryModal" class="modal"><div class="modal-content"><div class="modal-header"><h3><i class="fas fa-plus-circle"></i> إضافة قسم</h3><span class="close-btn">&times;</span></div><form id="addCategoryForm"><div class="form-group"><label for="categoryName">اسم القسم</label><input type="text" id="categoryName" required></div><div class="form-group"><label for="categoryIcon">أيقونة</label><select id="categoryIcon" required><option value="">اختر</option><option value="fas fa-coffee">☕ قهوة</option><option value="fas fa-glass-whiskey">🥃 مشروبات</option></select></div><div class="modal-footer"><button type="button" class="btn-cancel">إلغاء</button><button type="submit" class="btn-save">حفظ</button></div></form></div></div>
    <div id="editCategoryModal" class="modal"><div class="modal-content"><div class="modal-header"><h3><i class="fas fa-edit"></i> تعديل قسم</h3><span class="close-btn">&times;</span></div><form id="editCategoryForm"><div class="form-group"><label for="editCategoryName">اسم القسم</label><input type="text" id="editCategoryName" required></div><div class="form-group"><label for="editCategoryIcon">أيقونة</label><select id="editCategoryIcon" required><option value="">اختر</option><option value="fas fa-coffee">☕ قهوة</option><option value="fas fa-glass-whiskey">🥃 مشروبات</option></select></div><div class="modal-footer"><button type="button" class="btn-cancel">إلغاء</button><button type="submit" class="btn-save">حفظ</button></div></form></div></div>
    <div id="productDetailsModal" class="modal"><div class="modal-content"><div class="modal-header"><h3><i class="fas fa-info-circle"></i> تفاصيل المنتج</h3><span class="close-btn">&times;</span></div><div class="product-details-content"><div class="detail-item"><span>الاسم:</span><span id="detailProductName"></span></div><div class="detail-item"><span>القسم:</span><span id="detailProductCategory"></span></div><div class="detail-item"><span>سعر الموظف:</span><span id="detailEmployeePrice"></span></div><div class="detail-item"><span>سعر العميل:</span><span id="detailCustomerPrice"></span></div><div class="detail-item"><span>المخزون:</span><span id="detailProductStock"></span></div><div class="detail-item"><span>الوصف:</span><span id="detailProductDescription"></span></div></div><div class="modal-footer"><button type="button" class="btn-cancel">إغلاق</button></div></div></div>
    <div id="categoryProductsModal" class="modal"><div class="modal-content" style="max-width: 800px;"><div class="modal-header"><h3><i class="fas fa-eye"></i> منتجات: <span id="categoryProductsTitle"></span></h3><span class="close-btn">&times;</span></div><div class="category-products-content"><div class="products-summary"><div class="summary-item"><span>إجمالي المنتجات:</span><span id="categoryTotalProducts"></span></div><div class="summary-item"><span>إجمالي المخزون:</span><span id="categoryTotalStock"></span></div></div><div class="products-table-container"><table class="products-table"><thead><tr><th>المنتج</th><th>سعر العميل</th><th>المخزون</th><th>الحالة</th></tr></thead><tbody id="categoryProductsTableBody"></tbody></table></div></div><div class="modal-footer"><button type="button" class="btn-cancel">إغلاق</button></div></div></div>
    <div id="deviceTypeDetailsModal" class="modal"><div class="modal-content"><div class="modal-header"><h3><i class="fas fa-info-circle"></i> تفاصيل نوع الجهاز</h3><span class="close-btn">&times;</span></div><div class="device-details-content"></div><div class="modal-footer"><button type="button" class="btn-cancel">إغلاق</button></div></div></div>
    <div id="addCouponModal" class="modal"><div class="modal-content"><div class="modal-header"><h3><i class="fas fa-plus-circle"></i> إضافة كوبون جديد</h3><span class="close-btn">&times;</span></div><form id="addCouponForm"><div class="form-row"><div class="form-group"><label for="couponCode">كود الكوبون</label><input type="text" id="couponCode" required></div><div class="form-group"><label for="couponName">اسم الكوبون</label><input type="text" id="couponName" required></div></div><div class="form-row"><div class="form-group"><label for="discountType">نوع الخصم</label><select id="discountType" required><option value="percentage">% نسبة</option><option value="fixed">مبلغ ثابت</option></select></div><div class="form-group"><label for="discountValue">قيمة الخصم</label><input type="number" id="discountValue" required></div></div><div class="form-row"><div class="form-group"><label for="couponStartDate">تاريخ البدء</label><input type="date" id="couponStartDate" required></div><div class="form-group"><label for="couponEndDate">تاريخ الانتهاء</label><input type="date" id="couponEndDate" required></div></div><div class="modal-footer"><button type="button" class="btn-cancel">إلغاء</button><button type="submit" class="btn-save">حفظ</button></div></form></div></div>
    <div id="editCouponModal" class="modal"><div class="modal-content"><div class="modal-header"><h3><i class="fas fa-edit"></i> تعديل كوبون</h3><span class="close-btn">&times;</span></div><form id="editCouponForm"><div class="form-row"><div class="form-group"><label for="editCouponCode">كود الكوبون</label><input type="text" id="editCouponCode" required></div><div class="form-group"><label for="editCouponName">اسم الكوبون</label><input type="text" id="editCouponName" required></div></div><div class="form-row"><div class="form-group"><label for="editDiscountType">نوع الخصم</label><select id="editDiscountType" required><option value="percentage">% نسبة</option><option value="fixed">مبلغ ثابت</option></select></div><div class="form-group"><label for="editDiscountValue">قيمة الخصم</label><input type="number" id="editDiscountValue" required></div></div><div class="form-row"><div class="form-group"><label for="editCouponStartDate">تاريخ البدء</label><input type="date" id="editCouponStartDate" required></div><div class="form-group"><label for="editCouponEndDate">تاريخ الانتهاء</label><input type="date" id="editCouponEndDate" required></div></div><div class="form-group"><label class="checkbox-label"><input type="checkbox" id="editIsActive"><span class="checkmark"></span><span>الكوبون نشط</span></label></div><div class="modal-footer"><button type="button" class="btn-cancel">إلغاء</button><button type="submit" class="btn-save">حفظ</button></div></form></div></div>

    <script src="../js/inventory.js"></script>
</body>
</html>